name: Render sequence diagrams

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl sed

      - name: Determine changed .txt files
        id: changes
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep '\.txt$' || true)
          echo "changed=$CHANGED"
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Render diagrams
        if: ${{ steps.changes.outputs.changed != '' }}
        run: |
          echo ${{ steps.changes.outputs.changed }}

      - name: Update README.md image list
        run: |
          # Create image markdown list
          find . -name \*.png -printf "%f\n" |sed -e 's/^/![]\(/' -e 's/$/\)/' > .diagrams.tmp

          #Clear Markers
          sed -zi 's/<!-- diagrams:start -->.*\(<!-- diagrams:end -->\|$\)/<!-- diagrams:start -->\n<!-- diagrams:end -->/' README.md

          # Replace content between markers
          sed -i -e '/<!-- diagrams:start -->/,/<!-- diagrams:end -->/{/<!-- diagrams:start -->/{p; r .diagrams.tmp
                     }; /<!-- diagrams:end -->/p; d}' README.md

          rm .diagrams.tmp

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update diagrams & README"
            git push
          fi

